version: 2

models:
  - name: stg_cnpjs
    description: "TBD"
    columns:
          - name: buyer_tax_id
            description: 'TBD'
            tests:
              - not_null
              - unique
  - name: stg_installments
    description: "TBD"
    columns:
          - name: invoice_id
            description: 'TBD'
            tests:
              - not_null
              - unique

  - name: dim_cnpjs
    description: "TBD"
    columns:
          - name: buyer_tax_id
            description: 'TBD'
            tests:
              - not_null
              - unique
  - name: dim_installments
    description: "TBD"
    columns:
          - name: invoice_id
            description: 'TBD'
            tests:
              - not_null
              - unique
  - name: daily_cnpj_metrics
    description: "TBD"
    columns:
          - name: buyer_tax_id
            description: 'TBD'
            tests:
              - not_null
              - unique